# Cloudflare Pages Functions用の出力ディレクトリ指定
pages_build_output_dir = ".open-next"
#:schema node_modules/wrangler/config-schema.json

name = "challecara"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

# 本番環境の設定
[env.production]
name = "challecara"

# プレビュー環境の設定
[env.preview]
name = "challecara-preview"
