#:schema node_modules/wrangler/config-schema.json

name = "challecara"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

# OpenNextのビルド出力 (Workersエントリポイント)
main = ".open-next/worker.js"

# 静的アセットの設定
[assets]
directory = ".open-next/assets"
binding = "ASSETS"
