#:schema node_modules/wrangler/config-schema.json

name = "challecara"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

# Cloudflare Pages用の設定
# OpenNextのビルド出力ディレクトリを指定
pages_build_output_dir = ".open-next"
