# Cloudflare Pages Configuration
# This file is used for local development with wrangler pages dev

name = "challecara"
compatibility_date = "2024-12-09"

# Pages-specific configuration is minimal
# Most configuration is done through the Cloudflare Dashboard or CLI commands
